### ISSUE TITLE
.then()/.fail()/.finally() order of operations

### ISSUE THREAD

**Issue by mm-gmbd** [electricimp/Promise#14]
What is the order of operations for the `.then()` / `.fail()` / `.finally()`? Or, is it simply the order in which they are chained together? Including this in the docs would be helpful :)

**Comment by mm-gmbd** [comment]
Also, is there a way to determine, other than by inspecting the data passed to `.finally()`, if the previous Promise (or chain of Promises) was successful or failed?

**Comment by myurasov** [comment]
@mm-gmbd Max, you're right – then bodies are called in the order of addition and finally() is just an alias to then() if nothing bad happens.

**Comment by myurasov** [comment]
As to the second question - if an exception happens in .then() body, all subsequent .then-s are not executed and .fail() handlers are called. Please let me know if you meant something other than that.

I'm going to revise the code to be closer to ES2015 behaviour of promises soon to stick to a well-known standard.

**Comment by myurasov** [comment]
Added requirement to handle exceptions in .then() as a separate issue #17
