### ISSUE TITLE
Unexpected error in  Promise.serial()

### ISSUE THREAD

**Issue by dbukhmastov** [electricimp/Promise#24]
Reject handler invokation is expected.

Scenario:
Promise.serial(true)
.then(function(res) {
server.log("Resolve handler is called " + res);
}, function(res) {
server.log("Reject handler is called " + res);
})

Log:
2017-03-01 16:34:55+0000 [Agent]  ERROR: the index 'len' does not exist
2017-03-01 16:34:55+0000 [Agent]  ERROR:   in unknown ...ricimp#promise.class.nut#3.0.0:220
2017-03-01 16:34:55+0000 [Agent]  ERROR:   from unknown ...ricimp#promise.class.nut#3.0.0:191

**Comment by ppetrosh** [comment]
As documented here https://github.com/electricimp/Promise I believe it is an expected behavior as 

> The parameter series is an array of promises and/or functions that return promises.

Probably we can add a check for the _series_ type. But not sure, how critical that is.

**Comment by dbukhmastov** [comment]
The same description ("The parameter series") is in the Promise.all() function BUT the behavior is different. so I think this is an issue.

Promise.all(true).then(function(res) { 
    server.log("Resolve handler is called " + res);
}, function(res) { 
    server.log("Reject handler is called " + res);
});
LOG:
2017-03-02 09:13:08+0000 [Agent]  Reject handler is called the index 'len' does not exist (line 243)

**Comment by ppetrosh** [comment]
Agree, not sure about the priority at this point though. Thanks @dbukhmastov for investigating!

**Comment by smittytone** [comment]
This will be addressed in 4.0.1
