### ISSUE TITLE
The behavior of Promise.then() should be the same in cases of wrong parameters

### ISSUE THREAD

**Issue by dbukhmastov** [electricimp/Promise#25]
Scenario:
Promise(function (resolve, reject) {
    resolve(1);
})
.then(testParam)
.then(function(res) { 
    server.log("Resolve handler is called " + res);
}, function(res) { 
    server.log("Reject handler is called " + res);
})

Case 1 - local testParam = "string"
2017-03-01 16:45:33+0000 [Agent]  Resolve handler is called 1

Case 2 - local testParam = function(){}
2017-03-01 16:45:07+0000 [Agent]  Reject handler is called wrong number of parameters

**Comment by ppetrosh** [comment]
Agree, this is something that probably needs to be fixed.
