### ISSUE TITLE
Errors inside `then` and default main promise function are not handled properly

### ISSUE THREAD

**Issue by ppetrosh** [electricimp/Promise#28]
#require "promise.class.nut:3.0.0"

Promise.resolve("value")
    .then(function(value) {
        ERROR
    });

Promise(function(resolve, reject) {_})
    .then(null, null);

**Comment by jayeheffernan** [comment]
What's the issue here?

**Comment by ppetrosh** [comment]
The issue is that any errors in the mentioned handers are silently suppressed by the library. It makes it impossible to locate and debug them.
