### ISSUE TITLE
Add more examples for series of actions

### ISSUE THREAD

**Issue by ppetrosh** [electricimp/Promise#34]
We need to introduce a "Recommended usage" section.

Let's consider a series of actions of two types:

- `Sync` - synchronous action 
- `Async` - asynchronous action

and two modes of execution of the series:

- `Sync` - the series of actions terminates if one of them fails
- `Async` - the series is considered to be fulfilled when all the actions complete (regardless of whether they are succeeded of railed).

Here is a table that describes the recommended implementation options:

|  Actions  | Execution   | Suggestions  | Examples |
|---|---|---|---|
| Sync   | Sync  | `.then`,<br>`.serial`, or<br> `.loop`  | |
| Async  | Sync   | `.serial` + `f() {return Promise(action)}`, <br> `.loop` + `f() {return Promise(action)}` or <br>`.then` + `return Promise(action)` | |
|  Async | Async  | `.all`,<br>`.loop`,<br>`.serial`, or<br>`.then` + `return Promise(action)`| |
|  Sync | Async  | N/A  | N/A |
|  Sync and Async | Sync | `.serial` + `f() {return Promise}` or <br>`.loop` + `f() {return Promise}` | |
|  Sync and Async | Async | N/A | N/A |

Each of the suggestions should have a link to the documentation and an example provided.

**Comment by fedorDev** [comment]
Ok

**Comment by betzrhodes** [comment]
Addressed in release 4.0.0 - https://github.com/electricimp/Promise/releases/tag/v4.0.0-docs-examples-improved
